### ISSUE TITLE
RangeError: register limit - support for Arrays bigger than 255

### ISSUE THREAD

**Issue by paulohefagundes** [ldx/libpac#7]
[pac_example.js.txt](https://github.com/ldx/libpac/files/1835468/pac_example.js.txt)
Hello, I've run across an issue. The libraries explodes when the pac script has for example, an Array of more than 255 items.

Attached is an example of a PAC file. Currently the array has 256 items, and it causes libpac to throw an error. But once I comment out one or more Array items, then libpac seems fine

```
[PAC] Failed to evaluate PAC file: RangeError: register limit (line 262).
Segmentation fault: 11
```

Could you make this limit greater?

**Comment by ldx** [comment]
@paulohefagundes can you give https://github.com/ldx/libpac/pull/8 a try? It simply pulls in Duktape 2.2.0, which does not seem to have this limitation.

**Comment by paulohefagundes** [comment]
that worked like a charm ❤️

**Comment by ldx** [comment]
Thanks, merged the PR :+1:
